name: ci

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Build, Test & Analyze
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Run linter
        run: npm run lint

      - name: Run check-types
        run: npm run check-types

      - name: Run tests
        run: npm run test
